#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
cd $dir
tmp=/tmp/tmp/$USER/ovl_$$

die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
test -n "$1" || die "No out-file"
test -n "$TEST_DIR" || die 'Not set [$TEST_DIR]'
test -d "$TEST_DIR" || die "Not a directory [$TEST_DIR]"
cp -r $TEST_DIR $tmp

cd $tmp
tar cf "$1" *
cd $dir
rm -rf $tmp
